export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSE_BY_ID_SUCCESS = 'FETCH_EXPENSE_BY_ID_SUCCESS';

export const LOCALE_MESSAGES_SUCCESS = 'LOCALE_CHANGE';
